/*
 * generated by Xtext 2.10.0
 */
package uk.standrews.cs.cs4402.dsl.idea.completion

import org.eclipse.xtext.idea.lang.AbstractXtextLanguage
import uk.standrews.cs.cs4402.dsl.idea.lang.DSLLanguage

class DSLCompletionContributor extends AbstractDSLCompletionContributor {
	new() {
		this(DSLLanguage.INSTANCE)
	}
	
	new(AbstractXtextLanguage lang) {
		super(lang)
		//custom rules here
	}
}
