/*
 * generated by Xtext 2.10.0
 */
package uk.standrews.cs.cs4402.dsl


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class DSLRuntimeModule extends AbstractDSLRuntimeModule {
}
