/*
 * generated by Xtext 2.10.0
 */
package uk.standrews.cs.cs4402.dsl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class DSLStandaloneSetup extends DSLStandaloneSetupGenerated {

	def static void doSetup() {
		new DSLStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
