/*
 * generated by Xtext 2.10.0
 */
package uk.standrews.cs.cs4402.dsl.idea.lang


class DSLFileType extends AbstractDSLFileType {
	public static final DSLFileType INSTANCE = new DSLFileType()
	
	new() {
		super(DSLLanguage.INSTANCE)
	}
}
