/*
 * generated by Xtext 2.10.0
 */
package uk.standrews.cs.cs4402.dsl.idea

import org.eclipse.xtext.ISetup
import org.eclipse.xtext.idea.extensions.EcoreGlobalRegistries

class DSLIdeaSetup implements ISetup {

	override createInjectorAndDoEMFRegistration() {
		EcoreGlobalRegistries.ensureInitialized
		new DSLStandaloneSetupIdea().createInjector
	}

}
