/*
 * generated by Xtext 2.10.0
 */
package uk.standrews.cs.cs4402.dsl.idea


/**
 * Use this class to register components to be used within IntelliJ IDEA.
 */
class DSLIdeaModule extends AbstractDSLIdeaModule {
}
